name: asyncvalue_practice
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  riverpod_annotation: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
